name: plantpal
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Temel Paketler
  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.4.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  geolocator: ^12.0.0
  http: ^1.2.1
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  curved_navigation_bar: ^1.0.3
  permission_handler: ^11.3.1
  
  # Arka Plan ve Bildirim Paketleri
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.2.1
  android_alarm_manager_plus: ^4.0.7

  # Firebase
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  firebase_core: ^3.2.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.1

  # UI ve Diğerleri
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_image_compress: ^2.3.0
  lottie: ^3.3.1
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Bu satırın var ve doğru girintide olduğundan emin olun

# --- FONTS BÖLÜMÜ ARTIK GEREKLİ OLMADIĞI İÇİN TAMAMEN KALDIRILDI ---

# pubspec.yaml dosyasının sonuna bunu ekleyin

# pubspec.yaml dosyasının sonuna bunu ekleyin

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png" # Yeni ve temiz ikon dosyamızın yolu
  remove_alpha_ios: true # iOS için şeffaflık sorununu önler

  # pubspec.yaml dosyasının sonuna ekleyin

# pubspec.yaml dosyasındaki flutter_native_splash bölümünü bununla değiştirin

# Lütfen mevcut flutter_native_splash bölümünü silip bunu yapıştırın
flutter_native_splash:
  # Açılış ekranının arka plan rengi
  color: "#FFFFFF"
  # Karanlık mod için arka plan rengi
  color_dark: "#FFFFFF"

  # Kendi logonuzun yolu
  image: assets/images/icon.png

  # Bu ayarların Android ve iOS için geçerli olduğunu belirtir
  android: true
  ios: true